syntax on
filetype indent plugin on

set backspace=indent,eol,start

set tabstop=4
set expandtab
set shiftwidth=4
set softtabstop=4

set number
set showcmd
set cursorline
set laststatus=2
set noshowmode
set wildmenu
set lazyredraw

set ignorecase
set showmatch
set incsearch
set hlsearch

set guifont=Hack\ Regular:h14

"set modeline
"set modelines=5

if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged') "load vim-plug
    Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'
    Plug 'psf/black'
call plug#end()

let g:airline_theme='badwolf'
hi Search term=reverse ctermbg=Green ctermfg=White guibg=Yellow

autocmd BufWritePre *.py execute ':Black'
